import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-background">
      <Navbar />
      
      <div className="container mx-auto max-w-4xl px-4 py-20 pt-32">
        <h1 className="font-serif text-primary text-4xl lg:text-5xl font-bold mb-4">
          SOLENA Terms of Service
        </h1>
        <p className="font-sans text-text/60 text-sm mb-12">
          Last Updated: January 17, 2026
        </p>

        {/* Legal Disclaimer */}
        <div className="bg-yellow-50 border-l-4 border-yellow-500 p-4 rounded mb-8">
          <p className="font-sans text-yellow-800 text-sm">
            <strong>⚠️ LEGAL DISCLAIMER:</strong> These documents are generated by an AI system for drafting purposes only. While they are designed to be comprehensive and protective, they do not constitute legal advice. Before deployment, these documents must be reviewed and finalized by qualified legal counsel licensed in South Korea and familiar with international technology law to ensure full compliance with local regulations and specific business circumstances.
          </p>
        </div>

        <div className="prose prose-slate max-w-none">
          <section className="mb-8">
            <h2 className="font-serif text-primary text-2xl font-bold mb-4">1. INTRODUCTION AND ACCEPTANCE</h2>
            <p className="font-sans text-text leading-relaxed mb-4">
              These Terms of Service ("Terms") constitute a legally binding agreement between you ("User," "you," or "your") and SOLENA ("SOLENA," "we," "us," or "our"), a company organized under the laws of the Republic of Korea, with offices at 95, Dongtan-daero 4-gil, Hwaseong-si, Gyeonggi-do, Republic of Korea.
            </p>
            <p className="font-sans text-text leading-relaxed mb-4">
              By accessing, registering for, or using the SOLENA platform, website (solenamedical.com), or any associated services (collectively, the "Services"), you expressly agree to be bound by these Terms.
            </p>
            <p className="font-sans text-text leading-relaxed mb-4 font-bold">
              IF YOU DO NOT AGREE TO THESE TERMS, DO NOT USE THE SERVICES.
            </p>
            <h3 className="font-serif text-primary text-xl font-bold mb-3 mt-6">1.1 Eligibility</h3>
            <p className="font-sans text-text leading-relaxed mb-4">
              You must be at least 18 years of age (or the age of majority in your jurisdiction) to use the Services. By using the Services, you represent and warrant that you have the legal capacity to enter into this agreement.
            </p>
            <h3 className="font-serif text-primary text-xl font-bold mb-3">1.2 EU/EEA Exclusion</h3>
            <p className="font-sans text-text leading-relaxed font-bold">
              THE SERVICES ARE NOT INTENDED FOR, AND MAY NOT BE USED BY, RESIDENTS OF THE EUROPEAN UNION (EU) OR THE EUROPEAN ECONOMIC AREA (EEA). Access to the Services is technically restricted in these regions. Any attempt to circumvent these restrictions via VPN or other means is a material breach of these Terms.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="font-serif text-primary text-2xl font-bold mb-4">2. SERVICES DESCRIPTION</h2>
            <p className="font-sans text-text leading-relaxed mb-4">
              SOLENA is an interactive, web-based regulatory intelligence platform designed to assist manufacturers in the healthcare and cosmetics industries. The Services utilize artificial intelligence ("AI"), vector search technology, and third-party Application Programming Interfaces ("APIs"), including but not limited to OpenFDA and the Korea Ministry of Food and Drug Safety (MFDS), to generate research reports.
            </p>
            <h3 className="font-serif text-primary text-xl font-bold mb-3">2.1 Nature of Services</h3>
            <p className="font-sans text-text leading-relaxed mb-4">
              The Services allow users to input parameters to generate HTML-based reports regarding regulatory landscapes. These reports are generated dynamically using Large Language Models (LLMs) and retrieval-augmented generation (RAG).
            </p>
            <h3 className="font-serif text-primary text-xl font-bold mb-3">2.2 MACHINE-GENERATED CONTENT WARNING</h3>
            <p className="font-sans text-text leading-relaxed mb-4 font-bold">
              YOU ACKNOWLEDGE THAT THE SERVICES RELY ON ARTIFICIAL INTELLIGENCE. REPORTS ARE GENERATED AUTOMATICALLY AND ARE NOT REVIEWED BY HUMANS.
            </p>
            <p className="font-sans text-text leading-relaxed mb-4 font-bold">
              IMPORTANT: MACHINE-GENERATED CONTENT DISCLAIMER
            </p>
            <p className="font-sans text-text leading-relaxed mb-4">
              All reports, analyses, data, and content generated through the SOLENA platform are produced using artificial intelligence, machine learning, and automated systems without human expert review, verification, or validation. SOLENA does not employ regulatory experts, legal professionals, medical professionals, or other qualified experts to review, verify, or validate any machine-generated content.
            </p>
            <p className="font-sans text-text leading-relaxed mb-2">Users acknowledge and agree that:</p>
            <ul className="font-sans text-text leading-relaxed space-y-2 list-disc list-inside mb-4">
              <li>Machine-generated content may contain errors, inaccuracies, omissions, outdated information, or incomplete data.</li>
              <li>Machine-generated content is based on publicly available information, third-party API data, and proprietary algorithms that may produce incorrect or misleading results.</li>
              <li>SOLENA makes no representations or warranties regarding the accuracy, completeness, timeliness, reliability, or suitability of any machine-generated content.</li>
              <li>SOLENA shall not be liable for any consequences, damages, losses, or liabilities arising from reliance on machine-generated content.</li>
              <li>Users must independently verify all information before making any business, legal, regulatory, or commercial decisions.</li>
              <li>Users should consult qualified professionals (legal, medical, regulatory, financial) before making decisions based on machine-generated content.</li>
              <li>Reports are informational only and do not constitute professional advice of any kind.</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="font-serif text-primary text-2xl font-bold mb-4">3. ACCOUNT REGISTRATION & SECURITY</h2>
            <h3 className="font-serif text-primary text-xl font-bold mb-3">3.1 Registration</h3>
            <p className="font-sans text-text leading-relaxed mb-4">
              To access the Services, you must register for an account using a valid email address or Google OAuth. You agree to provide accurate, current, and complete information during the registration process.
            </p>
            <h3 className="font-serif text-primary text-xl font-bold mb-3">3.2 Account Security</h3>
            <p className="font-sans text-text leading-relaxed mb-4">
              You are responsible for maintaining the confidentiality of your credentials. You are solely responsible for all activities that occur under your account. You agree not to share your account credentials with any third party.
            </p>
            <h3 className="font-serif text-primary text-xl font-bold mb-3">3.3 Account Termination</h3>
            <p className="font-sans text-text leading-relaxed">
              SOLENA reserves the right to suspend or terminate your account at any time, with or without cause, including for violations of these Terms. You may terminate your account at any time via the platform settings.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="font-serif text-primary text-2xl font-bold mb-4">4. PAYMENT, PRICING, AND SUBSCRIPTIONS</h2>
            <h3 className="font-serif text-primary text-xl font-bold mb-3">4.1 Subscription Basis</h3>
            <p className="font-sans text-text leading-relaxed mb-4">
              The Services are offered on a subscription basis. Specific features, usage limits, and pricing are defined by your selected subscription tier. Detailed pricing information is available through our sales representatives, designated vendors, or by contacting us at info@solenamedical.com.
            </p>
            <h3 className="font-serif text-primary text-xl font-bold mb-3">4.2 Billing and Payment</h3>
            <p className="font-sans text-text leading-relaxed mb-4">
              Payments are processed by third-party payment processors. You authorize us to charge your payment method for the applicable subscription fees on a recurring basis (monthly or annually) until you cancel.
            </p>
            <h3 className="font-serif text-primary text-xl font-bold mb-3">4.3 No Refunds</h3>
            <p className="font-sans text-text leading-relaxed mb-4 font-bold">
              ALL SALES ARE FINAL. Subscription fees are non-refundable, except as required by applicable law.
            </p>
            <h3 className="font-serif text-primary text-xl font-bold mb-3">4.4 Taxes</h3>
            <p className="font-sans text-text leading-relaxed">
              You are responsible for all applicable taxes, levies, or duties imposed by taxing authorities.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="font-serif text-primary text-2xl font-bold mb-4">5. PLATFORM FEATURES AND LIMITATIONS</h2>
            <h3 className="font-serif text-primary text-xl font-bold mb-3">5.1 Service Availability</h3>
            <p className="font-sans text-text leading-relaxed mb-4">
              SOLENA does not guarantee that the Services will be available at all times. We may experience hardware, software, or other problems or need to perform maintenance related to the Platform, resulting in interruptions, delays, or errors.
            </p>
            <h3 className="font-serif text-primary text-xl font-bold mb-3">5.2 Third-Party API Liability</h3>
            <p className="font-sans text-text leading-relaxed mb-2">
              The Services integrate data from third-party sources (e.g., OpenFDA, MFDS).
            </p>
            <ul className="font-sans text-text leading-relaxed space-y-2 list-disc list-inside">
              <li>SOLENA does not control, verify, or guarantee the accuracy of data provided by third-party APIs.</li>
              <li>SOLENA is not responsible for outages, rate limits, or discontinuation of third-party APIs.</li>
              <li>Any reliance on data retrieved via third-party APIs is at your own risk.</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="font-serif text-primary text-2xl font-bold mb-4">6. INTELLECTUAL PROPERTY</h2>
            <h3 className="font-serif text-primary text-xl font-bold mb-3">6.1 SOLENA Ownership</h3>
            <p className="font-sans text-text leading-relaxed mb-4">
              SOLENA and its licensors own all rights, title, and interest in and to the Services, including all software, source code, algorithms, UI design, and logos.
            </p>
            <h3 className="font-serif text-primary text-xl font-bold mb-3">6.2 User License</h3>
            <p className="font-sans text-text leading-relaxed mb-4">
              Subject to your compliance with these Terms, SOLENA grants you a limited, non-exclusive, non-transferable, revocable license to access and use the Services for your internal business purposes.
            </p>
            <h3 className="font-serif text-primary text-xl font-bold mb-3">6.3 Restrictions</h3>
            <p className="font-sans text-text leading-relaxed">
              You shall not: (a) reverse engineer, decompile, or disassemble the Services; (b) use the Services to build a competitive product; (c) resell or sublicense the Services; or (d) scrape or systematically extract data from the Services.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="font-serif text-primary text-2xl font-bold mb-4">7. ACCEPTABLE USE</h2>
            <p className="font-sans text-text leading-relaxed mb-2">
              You agree not to use the Services for any unlawful purpose or in any way that interrupts, damages, or impairs the service. You are strictly prohibited from:
            </p>
            <ul className="font-sans text-text leading-relaxed space-y-2 list-disc list-inside">
              <li>Using the Services for medical diagnosis or treatment decisions.</li>
              <li>Sharing account credentials.</li>
              <li>Attempting to bypass security measures or geographic restrictions.</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="font-serif text-primary text-2xl font-bold mb-4">8. DISCLAIMERS</h2>
            <p className="font-sans text-text leading-relaxed mb-4 font-bold">
              THE SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, ACCURACY, COMPLETENESS, OR UNINTERRUPTED OPERATION. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, SOLENA EXPLICITLY DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED.
            </p>
            <h3 className="font-serif text-primary text-xl font-bold mb-3">8.1 No Professional Advice</h3>
            <p className="font-sans text-text leading-relaxed mb-4">
              The reports generated by SOLENA are for informational purposes only. They do NOT constitute legal, medical, regulatory, or financial advice. You must consult with qualified professionals before making any decisions based on the content provided.
            </p>
            <h3 className="font-serif text-primary text-xl font-bold mb-3">8.2 Data Accuracy</h3>
            <p className="font-sans text-text leading-relaxed">
              SOLENA explicitly disclaims any liability for errors, inaccuracies, or omissions in the reports, whether caused by AI hallucinations, vector search errors, or inaccuracies in source data (OpenFDA/MFDS).
            </p>
          </section>

          <section className="mb-8">
            <h2 className="font-serif text-primary text-2xl font-bold mb-4">9. LIMITATION OF LIABILITY</h2>
            <p className="font-sans text-text leading-relaxed mb-4 font-bold">
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL SOLENA, ITS AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, OR LICENSORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, PUNITIVE, OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO LOST PROFITS, LOST DATA, BUSINESS INTERRUPTION, LOST OPPORTUNITIES, OR DAMAGES ARISING FROM RELIANCE ON MACHINE-GENERATED CONTENT, REGARDLESS OF THE THEORY OF LIABILITY (CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR OTHERWISE), EVEN IF SOLENA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
            </p>
            <p className="font-sans text-text leading-relaxed mb-4 font-bold">
              SOLENA'S TOTAL LIABILITY FOR ANY CLAIMS ARISING OUT OF OR RELATING TO THESE TERMS OR THE SERVICES SHALL NOT EXCEED THE AMOUNT PAID BY YOU TO SOLENA IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR THE MINIMUM AMOUNT PERMITTED BY APPLICABLE LAW, WHICHEVER IS GREATER.
            </p>
            <p className="font-sans text-text leading-relaxed font-bold">
              NO ACTION, REGARDLESS OF FORM, ARISING OUT OF OR RELATING TO THESE TERMS OR THE SERVICES MAY BE BROUGHT BY YOU MORE THAN TWELVE (12) MONTHS AFTER THE CAUSE OF ACTION ACCRUED, OR THE MINIMUM PERIOD PERMITTED BY APPLICABLE LAW, WHICHEVER IS SHORTER.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="font-serif text-primary text-2xl font-bold mb-4">10. INDEMNIFICATION</h2>
            <p className="font-sans text-text leading-relaxed mb-2">
              You agree to indemnify, defend, and hold harmless SOLENA and its respective officers, directors, employees, and agents from and against any and all claims, liabilities, damages, losses, costs, expenses, or fees (including reasonable attorneys' fees) arising from:
            </p>
            <ul className="font-sans text-text leading-relaxed space-y-2 list-disc list-inside">
              <li>Your use or misuse of the Services;</li>
              <li>Your violation of these Terms;</li>
              <li>Your reliance on any machine-generated content or reports;</li>
              <li>Any business decisions made by you based on the Services;</li>
              <li>Your violation of any rights of a third party or any applicable laws or regulations.</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="font-serif text-primary text-2xl font-bold mb-4">11. TERMINATION</h2>
            <p className="font-sans text-text leading-relaxed">
              SOLENA may terminate or suspend your access to the Services immediately, without prior notice or liability, for any reason, including limitation if you breach these Terms. Upon termination, your right to use the Services will immediately cease. Sections 6 (IP), 8 (Disclaimers), 9 (Limitation of Liability), 10 (Indemnification), and 13 (Governing Law) shall survive termination.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="font-serif text-primary text-2xl font-bold mb-4">12. FORCE MAJEURE</h2>
            <p className="font-sans text-text leading-relaxed">
              SOLENA shall not be liable for any delay or failure to perform resulting from causes outside its reasonable control, including, but not limited to, acts of God, war, terrorism, riots, embargos, acts of civil or military authorities, fire, floods, accidents, strikes or shortages of transportation facilities, fuel, energy, labor or materials, or failures of third-party service providers (including Google Cloud, OpenFDA, or MFDS).
            </p>
          </section>

          <section className="mb-8">
            <h2 className="font-serif text-primary text-2xl font-bold mb-4">13. GOVERNING LAW AND DISPUTE RESOLUTION</h2>
            <h3 className="font-serif text-primary text-xl font-bold mb-3">13.1 Governing Law</h3>
            <p className="font-sans text-text leading-relaxed mb-4">
              These Terms shall be governed by and construed in accordance with the laws of the Republic of Korea, without regard to its conflict of law provisions.
            </p>
            <h3 className="font-serif text-primary text-xl font-bold mb-3">13.2 Jurisdiction</h3>
            <p className="font-sans text-text leading-relaxed mb-4">
              Any legal suit, action, or proceeding arising out of or related to these Terms or the Services shall be instituted exclusively in the Seoul Central District Court in Seoul, Republic of Korea. You waive any and all objections to the exercise of jurisdiction over you by such courts and to venue in such courts.
            </p>
            <h3 className="font-serif text-primary text-xl font-bold mb-3">13.3 Class Action Waiver</h3>
            <p className="font-sans text-text leading-relaxed">
              Where permitted under applicable law, you and SOLENA agree that each may bring claims against the other only in your or its individual capacity and not as a plaintiff or class member in any purported class or representative action.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="font-serif text-primary text-2xl font-bold mb-4">14. INTERNATIONAL USE</h2>
            <p className="font-sans text-text leading-relaxed">
              The Services are controlled and operated from the Republic of Korea. We make no representation that the Services are appropriate or available for use in other locations. Those who access or use the Services from other jurisdictions do so at their own volition and are responsible for compliance with local law. Access to the Services from the European Union or European Economic Area is prohibited.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="font-serif text-primary text-2xl font-bold mb-4">15. CONTACT INFORMATION</h2>
            <p className="font-sans text-text leading-relaxed mb-4">
              If you have any questions about these Terms, please contact us at:
            </p>
            <p className="font-sans text-text leading-relaxed">
              <strong>SOLENA</strong><br />
              95, Dongtan-daero 4-gil, Hwaseong-si, Gyeonggi-do, Republic of Korea<br />
              Email: info@solenamedical.com
            </p>
          </section>
        </div>
      </div>

      <Footer />
    </main>
  );
}
